name: tonik_parse
description: The parsing module for Tonik.
version: 0.0.9
repository: https://github.com/t-unit/tonik
resolution: workspace

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  json_annotation: ^4.9.0
  logging: ^1.3.0
  tonik_core: ^0.0.9

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.8.0
  test: ^1.24.0
  very_good_analysis: ^10.0.0
