name: tonik_parse
description: The parsing module for Tonik.
version: 0.5.0
repository: https://github.com/t-unit/tonik
resolution: workspace

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  collection: ^1.19.1
  json_annotation: ^4.9.0
  logging: ^1.3.0
  tonik_core: ^0.5.0

dev_dependencies:
  build_runner: ^2.9.0
  json_serializable: ^6.11.1
  test: ^1.26.3
  very_good_analysis: ^10.0.0
