name: form_urlencoded_test
description: Integration tests for form-urlencoded content type support
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  dio: ^5.8.0
  form_urlencoded_api:
    path: ../form_urlencoded_api
  path: ^1.9.1
  tonik_util: ^0.1.0

dev_dependencies:
  test: ^1.25.15
  test_helpers:
    path: ../../test_helpers
  very_good_analysis: ^10.0.0

dependency_overrides:
  tonik_util:
    path: ../../../packages/tonik_util
