name: query_parameters_test
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  dio: ^5.8.0
  path: ^1.9.1
  query_parameters_api:
    path: ../query_parameters_api
  tonik_util: ^0.1.0

dev_dependencies:
  big_decimal: ^0.5.0
  test: ^1.25.15
  very_good_analysis: ^10.0.0


dependency_overrides:
  tonik_util:
    path: ../../../packages/tonik_util
