name: petstore_test
description: A test suite for the petstore API.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  dio: ^5.8.0
  path: ^1.9.1
  petstore_api:
    path: ../petstore_api
  tonik_util: ^0.4.1

dev_dependencies:
  test: ^1.25.15
  test_helpers:
    path: ../../test_helpers
  very_good_analysis: ^10.0.0



dependency_overrides:
  tonik_util:
    path: ../../../packages/tonik_util
