name: tonik_generate
description: A code generation package for Tonik.
version: 0.2.1
repository: https://github.com/t-unit/tonik
resolution: workspace

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  change_case: ^2.2.0
  code_builder: ^4.11.0
  collection: ^1.19.1
  dart_style: ^3.1.2
  logging: ^1.3.0
  meta: ^1.17.0
  path: ^1.9.1
  tonik_core: ^0.2.1
  tonik_util: ^0.2.1

dev_dependencies:
  test: ^1.26.3
  very_good_analysis: ^10.0.0
