name: tonik_core
description: Core data structures and utilities for Tonik.
version: 0.2.1
repository: https://github.com/t-unit/tonik
resolution: workspace

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  collection: ^1.19.1
  logging: ^1.3.0
  meta: ^1.17.0
  tonik_util: ^0.2.1

dev_dependencies:
  build_runner: ^2.9.0
  test: ^1.26.3
  very_good_analysis: ^10.0.0
  
