name: tonik
description: A Dart code generator for OpenAPI 3.0 and 3.1 specifications.
version: 0.1.0
repository: https://github.com/t-unit/tonik
resolution: workspace

executables:
  tonik: tonik

topics:
  - openapi
  - codegeneration
  - api
  - rest
  - swagger

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  args: ^2.7.0
  collection: ^1.19.1
  logging: ^1.3.0
  meta: ^1.17.0
  tonik_core: ^0.1.0
  tonik_generate: ^0.1.0
  tonik_parse: ^0.1.0
  yaml: ^3.1.3

dev_dependencies:
  path: ^1.9.1
  test: ^1.26.3
  very_good_analysis: ^10.0.0
